# Force PipeWire as audio output
# ao=pipewire
#
# # Try to keep original channel layout (don’t auto-downmix)
# audio-channels=auto

# If you only want 2ch downmixing, enforce it:
audio-channels=stereo

# If you want to always upmix/downmix to 5.1:
# audio-channels=5.1

# Control mixing behavior
# audio-normalize-downmix=no   # preserve relative volume when downmixing
# audio-spdif=ac3,dts          # passthrough for receivers if supported
#
# # Show current audio info (status line)
# msg-level=ao=infohwdec=auto
#
volume-max=100
save-position-on-quit

screenshot-template="%F - [%P] (%#01n)"


# mpv --profile=firefox --profile=ytdlp-firefox URL

[ytdlp-firefox]
ytdl-raw-options=
    user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0


# mpv --profile=firefox --profile=cookies URL
[cookies]
cookies=yes
cookies-file=~/.mozilla/firefox/PROFILE.default-release/cookies.sqlite

[voyo]
http-header-fields=User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0,Referer: https://voyo.si/,Origin: https://voyo.si
