cursor #171c1f
cursor_text_color #40484b

foreground            #171c1f
background            #f5fafd
selection_foreground  #ffffff
selection_background  #b3cad4
url_color             #01677d

# black
color8   #171c1f
color0   #4c4c4c

# red
color1   #ba1a1a
color9   #c49ea0

# green
color2   #171c1f
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
/* color4  #8f8aac */
color4  #01677d
color12 #a39ec4

# magenta
color5   #ba1a1a
color13  #c49ec4

# cyan
color6   #171c1f
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0